'use client';

import { Brain, Clock, RefreshCw, Database, BarChart3 } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import type { GenerateResult } from '@/lib/daily-ai-picks/generate';

interface Props {
  result: GenerateResult | null;
}

function formatMarkdown(text: string): string {
  // Convert markdown bold to HTML
  let html = text
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/^### (.+)$/gm, '<h3 class="text-lg font-bold mt-6 mb-2 text-primary">$1</h3>')
    .replace(/^## (.+)$/gm, '<h2 class="text-xl font-bold mt-8 mb-3 text-foreground border-b border-border pb-2">$1</h2>')
    .replace(/^# (.+)$/gm, '<h1 class="text-2xl font-bold mt-4 mb-4 text-foreground">$1</h1>')
    .replace(/^- (.+)$/gm, '<li class="ml-4 mb-1">$1</li>')
    .replace(/\n\n/g, '<br/><br/>')
    .replace(/\n/g, '<br/>');

  // Wrap consecutive <li> in <ul>
  html = html.replace(/((?:<li[^>]*>.*?<\/li>\s*<br\/>?\s*)+)/g, '<ul class="list-disc space-y-1 my-2">$1</ul>');

  return html;
}

export function DailyAIPicksContent({ result }: Props) {
  const today = new Date().toLocaleDateString('en-US', {
    weekday: 'long', month: 'long', day: 'numeric', year: 'numeric',
    timeZone: 'America/New_York',
  });

  if (!result) {
    return (
      <div className="container max-w-4xl py-8 px-4">
        <div className="text-center py-20">
          <Brain className="h-16 w-16 mx-auto mb-4 text-muted-foreground" />
          <h1 className="text-2xl font-bold mb-2">DailyAI Picks</h1>
          <p className="text-muted-foreground">
            Report is generating... Refresh in a minute.
          </p>
        </div>
      </div>
    );
  }

  const generatedTime = new Date(result.generatedAt).toLocaleTimeString('en-US', {
    hour: 'numeric', minute: '2-digit', timeZone: 'America/New_York',
  });

  return (
    <div className="container max-w-4xl py-8 px-4">
      {/* Header */}
      <div className="mb-8">
        <div className="flex items-center gap-3 mb-2">
          <Brain className="h-8 w-8 text-primary" />
          <h1 className="text-3xl font-bold">DailyAI Picks</h1>
          <Badge variant="secondary" className="text-xs">
            {result.cached ? 'Cached' : 'Fresh'}
          </Badge>
        </div>
        <p className="text-lg text-muted-foreground">{today}</p>

        {/* Stats bar */}
        <div className="flex flex-wrap gap-4 mt-4 text-sm text-muted-foreground">
          <span className="flex items-center gap-1">
            <Clock className="h-4 w-4" />
            Updated {generatedTime} ET
          </span>
          <span className="flex items-center gap-1">
            <RefreshCw className="h-4 w-4" />
            Refreshes hourly
          </span>
          {result.dataStats.expertPicks > 0 && (
            <span className="flex items-center gap-1">
              <Database className="h-4 w-4" />
              {result.dataStats.expertPicks} expert picks
            </span>
          )}
          {result.dataStats.prizePicksProps > 0 && (
            <span className="flex items-center gap-1">
              <BarChart3 className="h-4 w-4" />
              {result.dataStats.prizePicksProps} PrizePicks props
            </span>
          )}
        </div>

        {/* Data source badges */}
        <div className="flex flex-wrap gap-2 mt-3">
          {result.dataStats.expertPicks > 0 && <Badge variant="outline">Expert Consensus</Badge>}
          {result.dataStats.hasBallparkPal && <Badge variant="outline">BallparkPal</Badge>}
          {result.dataStats.hasStatcast && <Badge variant="outline">Statcast</Badge>}
          {result.dataStats.prizePicksProps > 0 && <Badge variant="outline">PrizePicks</Badge>}
          {result.dataStats.mlbGames > 0 && <Badge variant="outline">MLB {result.dataStats.mlbGames} games</Badge>}
          {result.dataStats.sportCount > 0 && <Badge variant="outline">ESPN {result.dataStats.sportCount} sports</Badge>}
        </div>
      </div>

      {/* Report content */}
      <div
        className="prose prose-invert max-w-none
          prose-h1:text-2xl prose-h2:text-xl prose-h3:text-lg
          prose-li:text-sm prose-p:text-sm
          prose-strong:text-primary"
        dangerouslySetInnerHTML={{ __html: formatMarkdown(result.report) }}
      />

      {/* Footer */}
      <div className="mt-12 pt-6 border-t border-border text-xs text-muted-foreground">
        <p>
          Generated by DailyAIPicks using Claude Sonnet. Data from BallparkPal, Baseball Savant,
          PrizePicks, MLB Stats API, ESPN, and {result.dataStats.cappers}+ expert cappers.
          Report refreshes every hour. Not financial advice.
        </p>
      </div>
    </div>
  );
}
