import { Metadata } from 'next';
import { notFound } from 'next/navigation';
import Link from 'next/link';
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Calendar, Eye, ArrowLeft, Share2 } from 'lucide-react';
import { EmailCaptureBanner } from '@/components/monetization/EmailCapture';
import { BlogPostingJsonLd } from '@/components/seo/JsonLd';

export const dynamic = 'force-dynamic';

interface PageProps {
  params: { slug: string };
}

interface BlogPost {
  id: string;
  slug: string;
  title: string;
  excerpt: string;
  content: string;
  category: string;
  sport: string | null;
  tags: string[];
  meta_title: string;
  meta_description: string;
  featured_image: string | null;
  published_at: string;
  view_count: number;
  ai_model: string;
}

const categoryLabels: Record<string, string> = {
  'daily-picks': 'Daily Picks',
  'preview': 'Game Preview',
  'recap': 'Recap',
  'analysis': 'Analysis',
};

async function getBlogPost(slug: string): Promise<BlogPost | null> {
  const baseUrl = process.env.NEXT_PUBLIC_BASE_URL || 'http://localhost:3000';
  
  try {
    const res = await fetch(`${baseUrl}/api/blog?slug=${encodeURIComponent(slug)}`, {
      cache: 'no-store',
    });
    const data = await res.json();
    return data.success && data.post ? data.post : null;
  } catch (error) {
    console.error('Failed to fetch blog post:', error);
    return null;
  }
}

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const post = await getBlogPost(params.slug);
  
  if (!post) {
    return {
      title: 'Article Not Found | DailyAI Betting',
      robots: { index: false, follow: false },
    };
  }

  return {
    title: post.meta_title || `${post.title} | DailyAI Betting`,
    description: post.meta_description || post.excerpt,
    keywords: post.tags?.join(', '),
  };
}

export default async function BlogPostPage({ params }: PageProps) {
  const post = await getBlogPost(params.slug);

  if (!post) {
    notFound();
  }

  const formatDate = (dateStr: string) => {
    return new Date(dateStr).toLocaleDateString('en-US', {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });
  };

  return (
    <div className="container px-4 py-8 max-w-3xl mx-auto">
      {/* Back Link */}
      <Link
        href="/blog"
        className="inline-flex items-center text-sm text-muted-foreground hover:text-primary mb-6 transition-colors"
      >
        <ArrowLeft className="h-4 w-4 mr-1" />
        Back to Blog
      </Link>

      {/* Blog Post Schema */}
      <BlogPostingJsonLd
        title={post.title}
        description={post.meta_description || post.excerpt}
        slug={post.slug}
        publishedAt={post.published_at}
        category={post.category}
        tags={post.tags}
        viewCount={post.view_count}
      />

      {/* Article Header */}
      <article>
        <header className="mb-8">
          <div className="flex items-center gap-2 mb-4">
            <Badge className="bg-primary">
              {categoryLabels[post.category] || post.category}
            </Badge>
            {post.sport && (
              <Badge variant="outline">{post.sport}</Badge>
            )}
          </div>

          <h1 className="text-3xl md:text-4xl font-bold mb-4">
            {post.title}
          </h1>

          <div className="flex items-center justify-between flex-wrap gap-4 text-sm text-muted-foreground">
            <div className="flex items-center gap-4">
              <span className="flex items-center gap-1">
                <Calendar className="h-4 w-4" />
                {formatDate(post.published_at)}
              </span>
              <span className="flex items-center gap-1">
                <Eye className="h-4 w-4" />
                {post.view_count} views
              </span>
            </div>
            <ShareButton />
          </div>
        </header>

        {/* Article Content */}
        <div
          className="prose prose-invert max-w-none mb-8"
          dangerouslySetInnerHTML={{ __html: post.content }}
        />

        {/* Tags */}
        {post.tags && post.tags.length > 0 && (
          <div className="flex flex-wrap gap-2 mb-8">
            {post.tags.map((tag) => (
              <Badge key={tag} variant="outline" className="text-xs">
                {tag}
              </Badge>
            ))}
          </div>
        )}

        {/* AI Attribution */}
        <Card className="mb-8 bg-muted/30">
          <CardContent className="p-4">
            <p className="text-sm text-muted-foreground">
              This article was generated by AI ({post.ai_model || 'GPT-4'}) based on expert consensus data.
              Always do your own research before placing bets.
            </p>
          </CardContent>
        </Card>
      </article>

      {/* Email Capture */}
      <EmailCaptureBanner />

      {/* Related Links */}
      <Card className="mt-8">
        <CardContent className="p-6">
          <h3 className="font-semibold mb-4">Continue Reading</h3>
          <div className="flex flex-wrap gap-2">
            <Button variant="outline" asChild>
              <Link href="/blog">More Articles</Link>
            </Button>
            <Button variant="outline" asChild>
              <Link href="/">Today&apos;s Consensus</Link>
            </Button>
            <Button variant="outline" asChild>
              <Link href="/daily-bets">Daily Bets</Link>
            </Button>
            <Button variant="outline" asChild>
              <Link href="/sportsbooks">Sportsbooks</Link>
            </Button>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}

// Client component for share functionality
function ShareButton() {
  return (
    <Button variant="ghost" size="sm" className="share-button" data-share="true">
      <Share2 className="h-4 w-4 mr-1" />
      Share
    </Button>
  );
}
