// Team name mappings - Comprehensive standardization
// Checks longer/more specific names first to avoid false matches

export const teamMappings: Record<string, Record<string, string[]>> = {
  MLB: {
    Diamondbacks: ['Diamondbacks', 'Arizona', 'Dbacks', 'D-backs', 'ARI', 'AZ'],
    Braves: ['Braves', 'Atlanta', 'ATL'],
    Orioles: ['Orioles', 'Baltimore', 'BAL', "O's"],
    'Red Sox': ['Red Sox', 'Boston', 'BOS', 'BoSox', 'RSox'],
    Cubs: ['Cubs', 'Chicago Cubs', 'CHC', 'Cubbies'],
    'White Sox': ['White Sox', 'Chicago White Sox', 'CWS', 'CHW', 'WSox'],
    Reds: ['Reds', 'Cincinnati', 'CIN'],
    Guardians: ['Guardians', 'Cleveland', 'CLE', 'Guards'],
    Rockies: ['Rockies', 'Colorado', 'COL'],
    Tigers: ['Tigers', 'Detroit', 'DET'],
    Astros: ['Astros', 'Houston', 'HOU', 'Stros'],
    Royals: ['Royals', 'Kansas City', 'KC', 'KCR'],
    Angels: ['Angels', 'Los Angeles Angels', 'LAA', 'Halos', 'Anaheim'],
    Dodgers: ['Dodgers', 'Los Angeles Dodgers', 'LAD'],
    Marlins: ['Marlins', 'Miami', 'MIA', 'Fish'],
    Brewers: ['Brewers', 'Milwaukee', 'MIL', 'Brew Crew'],
    Twins: ['Twins', 'Minnesota', 'MIN'],
    Yankees: ['Yankees', 'New York Yankees', 'NYY', 'Yanks', 'Bronx Bombers'],
    Mets: ['Mets', 'New York Mets', 'NYM'],
    Athletics: ['Athletics', 'Oakland', "A's", 'As', 'OAK'],
    Phillies: ['Phillies', 'Philadelphia', 'PHI', 'Phils'],
    Pirates: ['Pirates', 'Pittsburgh', 'PIT', 'Bucs'],
    Padres: ['Padres', 'San Diego', 'SD', 'SDP', 'Pads'],
    'Giants (MLB)': ['Giants', 'San Francisco', 'SF', 'SFG'],
    Mariners: ['Mariners', 'Seattle', 'SEA', "M's"],
    Cardinals: ['Cardinals', 'St Louis', 'STL', 'St. Louis', 'Cards', 'Redbirds'],
    Rays: ['Rays', 'Tampa Bay', 'TB', 'TBR'],
    'Rangers (MLB)': ['Rangers', 'Texas', 'TEX'],
    'Blue Jays': ['Blue Jays', 'Toronto', 'TOR', 'Jays'],
    Nationals: ['Nationals', 'Washington', 'WAS', 'WSH', 'Nats'],
  },
  NBA: {
    Hawks: ['Hawks', 'Atlanta', 'ATL'],
    Celtics: ['Celtics', 'Boston', 'BOS', 'Cs'],
    Nets: ['Nets', 'Brooklyn', 'BKN', 'BRK'],
    Hornets: ['Hornets', 'Charlotte', 'CHA', 'CHO', 'Buzz'],
    Bulls: ['Bulls', 'Chicago', 'CHI'],
    Cavaliers: ['Cavaliers', 'Cleveland', 'CLE', 'Cavs'],
    Mavericks: ['Mavericks', 'Dallas', 'DAL', 'Mavs'],
    Nuggets: ['Nuggets', 'Denver', 'DEN', 'Nugs'],
    Pistons: ['Pistons', 'Detroit', 'DET'],
    Warriors: ['Warriors', 'Golden State', 'GS', 'GSW', 'Dubs'],
    Rockets: ['Rockets', 'Houston', 'HOU', 'Rox'],
    Pacers: ['Pacers', 'Indiana', 'IND'],
    Clippers: ['Clippers', 'Los Angeles Clippers', 'LAC', 'LA Clippers', 'Clips'],
    Lakers: ['Lakers', 'Los Angeles Lakers', 'LAL', 'LA Lakers'],
    Grizzlies: ['Grizzlies', 'Memphis', 'MEM', 'Grizz'],
    Heat: ['Heat', 'Miami', 'MIA'],
    Bucks: ['Bucks', 'Milwaukee', 'MIL'],
    Timberwolves: ['Timberwolves', 'Minnesota', 'MIN', 'Wolves', 'TWolves', "T'Wolves", 'T-Wolves'],
    Pelicans: ['Pelicans', 'New Orleans', 'NO', 'NOP', 'Pels'],
    Knicks: ['Knicks', 'New York', 'NY', 'NYK'],
    Thunder: ['Thunder', 'Oklahoma City', 'OKC'],
    Magic: ['Magic', 'Orlando', 'ORL'],
    '76ers': ['76ers', 'Philadelphia', 'PHI', 'Sixers'],
    Suns: ['Suns', 'Phoenix', 'PHX', 'PHO'],
    'Trail Blazers': ['Trail Blazers', 'Portland', 'POR', 'Blazers'],
    Kings: ['Kings', 'Sacramento', 'SAC'],
    Spurs: ['Spurs', 'San Antonio', 'SA', 'SAS'],
    Raptors: ['Raptors', 'Toronto', 'TOR', 'Raps'],
    Jazz: ['Jazz', 'Utah', 'UTA'],
    Wizards: ['Wizards', 'Washington', 'WAS', 'WSH', 'Wiz'],
  },
  NFL: {
    Cardinals: ['Cardinals', 'Arizona', 'ARI', 'ARZ', 'Cards'],
    Falcons: ['Falcons', 'Atlanta', 'ATL', 'Dirty Birds'],
    Ravens: ['Ravens', 'Baltimore', 'BAL', 'Balt'],
    Bills: ['Bills', 'Buffalo', 'BUF', 'Buff'],
    Panthers: ['Panthers', 'Carolina', 'CAR', 'Caro'],
    Bears: ['Bears', 'Chicago', 'CHI'],
    Bengals: ['Bengals', 'Cincinnati', 'CIN', 'Cincy'],
    Browns: ['Browns', 'Cleveland', 'CLE', 'Clev'],
    Cowboys: ['Cowboys', 'Dallas', 'DAL'],
    Broncos: ['Broncos', 'Denver', 'DEN', 'Denv'],
    Lions: ['Lions', 'Detroit', 'DET'],
    Packers: ['Packers', 'Green Bay', 'GB', 'GNB', 'Pack'],
    Texans: ['Texans', 'Houston', 'HOU', 'Houst'],
    Colts: ['Colts', 'Indianapolis', 'IND', 'Indy'],
    Jaguars: ['Jaguars', 'Jacksonville', 'JAX', 'JAC', 'Jags'],
    Chiefs: ['Chiefs', 'Kansas City', 'KC', 'KAN', 'KCity'],
    Raiders: ['Raiders', 'Las Vegas', 'LV', 'LVR', 'Oak', 'Oakland'],
    Chargers: ['Chargers', 'Los Angeles Chargers', 'LAC', 'LA Chargers'],
    Rams: ['Rams', 'Los Angeles Rams', 'LAR', 'LA Rams'],
    Dolphins: ['Dolphins', 'Miami', 'MIA', 'Phins'],
    Vikings: ['Vikings', 'Minnesota', 'MIN', 'Minn', 'Vikes'],
    Patriots: ['Patriots', 'New England', 'NE', 'NEP', 'Pats'],
    Saints: ['Saints', 'New Orleans', 'NO', 'NOS', 'Nawlins'],
    'Giants (NFL)': ['Giants', 'New York Giants', 'NYG', 'NY Giants'],
    'Jets (NFL)': ['Jets', 'New York Jets', 'NYJ', 'NY Jets'],
    Eagles: ['Eagles', 'Philadelphia', 'PHI', 'Philly'],
    Steelers: ['Steelers', 'Pittsburgh', 'PIT', 'Pitt'],
    '49ers': ['49ers', 'San Francisco', 'SF', 'SFO', 'Niners'],
    Seahawks: ['Seahawks', 'Seattle', 'SEA', 'Hawks'],
    Buccaneers: ['Buccaneers', 'Tampa Bay', 'TB', 'TAM', 'Bucs'],
    Titans: ['Titans', 'Tennessee', 'TEN', 'Tenn'],
    Commanders: ['Commanders', 'Washington', 'WAS', 'WSH', 'Commies'],
  },
  NHL: {
    Ducks: ['Ducks', 'Anaheim', 'ANA'],
    'Utah HC': ['Utah HC', 'Utah', 'UTA', 'Coyotes', 'Arizona Coyotes'],
    Bruins: ['Bruins', 'Boston', 'BOS', 'Bs'],
    Sabres: ['Sabres', 'Buffalo', 'BUF'],
    Flames: ['Flames', 'Calgary', 'CGY', 'CAL'],
    Hurricanes: ['Hurricanes', 'Carolina', 'CAR', 'Canes'],
    Blackhawks: ['Blackhawks', 'Chicago', 'CHI'],
    Avalanche: ['Avalanche', 'Colorado', 'COL', 'Avs'],
    'Blue Jackets': ['Blue Jackets', 'Columbus', 'CBJ', 'CLB', 'Jackets'],
    Stars: ['Stars', 'Dallas', 'DAL'],
    'Red Wings': ['Red Wings', 'Detroit', 'DET', 'Wings'],
    Oilers: ['Oilers', 'Edmonton', 'EDM', 'Oil'],
    'Panthers (NHL)': ['Panthers', 'Florida', 'FLA', 'Cats'],
    'Kings (NHL)': ['Kings', 'Los Angeles', 'LAK', 'LA'],
    Wild: ['Wild', 'Minnesota', 'MIN'],
    Canadiens: ['Canadiens', 'Montreal', 'MTL', 'MON', 'Habs'],
    Predators: ['Predators', 'Nashville', 'NSH', 'NAS', 'Preds'],
    Devils: ['Devils', 'New Jersey', 'NJD', 'NJ'],
    Islanders: ['Islanders', 'New York Islanders', 'NYI', 'Isles'],
    'Rangers (NHL)': ['Rangers', 'New York Rangers', 'NYR'],
    Senators: ['Senators', 'Ottawa', 'OTT', 'Sens'],
    Flyers: ['Flyers', 'Philadelphia', 'PHI'],
    Penguins: ['Penguins', 'Pittsburgh', 'PIT', 'Pens'],
    Sharks: ['Sharks', 'San Jose', 'SJ', 'SJS'],
    Kraken: ['Kraken', 'Seattle', 'SEA'],
    Blues: ['Blues', 'St Louis', 'STL', 'St. Louis'],
    Lightning: ['Lightning', 'Tampa Bay', 'TB', 'TBL', 'Bolts'],
    'Maple Leafs': ['Maple Leafs', 'Toronto', 'TOR', 'Leafs'],
    Canucks: ['Canucks', 'Vancouver', 'VAN', 'Nucks'],
    'Golden Knights': ['Golden Knights', 'Vegas', 'VGK', 'VEG', 'Knights'],
    Capitals: ['Capitals', 'Washington', 'WAS', 'WSH', 'Caps'],
    'Jets (NHL)': ['Jets', 'Winnipeg', 'WPG', 'WIN'],
  },
  WNBA: {
    Dream: ['Dream', 'Atlanta'],
    Sky: ['Sky', 'Chicago'],
    Sun: ['Sun', 'Connecticut', 'CON', 'CT'],
    Wings: ['Wings', 'Dallas'],
    Fever: ['Fever', 'Indiana'],
    Aces: ['Aces', 'Las Vegas', 'LV', 'LVA'],
    Sparks: ['Sparks', 'Los Angeles', 'LAS'],
    Lynx: ['Lynx', 'Minnesota'],
    'Liberty (WNBA)': ['Liberty', 'New York', 'NYL'],
    Mercury: ['Mercury', 'Phoenix'],
    Storm: ['Storm', 'Seattle'],
    Mystics: ['Mystics', 'Washington'],
    Valkyries: ['Valkyries', 'Golden State', 'GSV'],
  },
  NCAAF: {
    // Group of 5 - Sun Belt (check first for specific names)
    'Georgia Southern': ['Georgia Southern', 'Georgia Southern Eagles', 'GASO', 'Ga Southern'],
    'Georgia State': ['Georgia State', 'Georgia State Panthers', 'Ga State'],
    'Georgia Tech': ['Georgia Tech', 'Yellow Jackets', 'GT', 'Ga Tech', 'Rambling Wreck'],
    'Appalachian State': ['Appalachian State', 'App State', 'APP', 'Mountaineers'],
    'Arkansas State': ['Arkansas State', 'ArkSt', 'ARST', 'Red Wolves'],
    'Coastal Carolina': ['Coastal Carolina', 'CCU', 'Coastal', 'Chanticleers'],
    'James Madison': ['James Madison', 'JMU', 'Dukes'],
    Louisiana: ['Louisiana', 'UL', 'Ragin Cajuns', 'Louisiana Ragin Cajuns'],
    'Louisiana Tech': ['Louisiana Tech', 'LaTech', 'LATECH'],
    Marshall: ['Marshall', 'MARSH', 'Thundering Herd'],
    'Old Dominion': ['Old Dominion', 'ODU', 'Monarchs'],
    'South Alabama': ['South Alabama', 'USA', 'Jaguars'],
    'Southern Miss': ['Southern Miss', 'USM', 'Golden Eagles', 'Southern Mississippi'],
    'Texas State': ['Texas State', 'TXST', 'Bobcats'],
    Troy: ['Troy', 'TROY', 'Trojans'],

    // Mountain West
    'Air Force': ['Air Force', 'AFA', 'AF', 'Falcons'],
    'Boise State': ['Boise State', 'Boise', 'BSU', 'Broncos'],
    'Colorado State': ['Colorado State', 'CSU', 'Colo St', 'Rams'],
    'Fresno State': ['Fresno State', 'Fresno', 'FRES'],
    Hawaii: ['Hawaii', 'HAW', 'Rainbow Warriors', 'Hawaii Rainbow Warriors'],
    Nevada: ['Nevada', 'NEV', 'Wolf Pack'],
    'New Mexico': ['New Mexico', 'UNM', 'NM', 'Lobos'],
    'San Diego State': ['San Diego State', 'SDSU', 'Aztecs'],
    'San Jose State': ['San Jose State', 'SJSU', 'Spartans'],
    UNLV: ['UNLV', 'Las Vegas', 'Rebels'],
    'Utah State': ['Utah State', 'USU', 'Aggies'],
    Wyoming: ['Wyoming', 'WYO', 'Cowboys'],

    // MAC
    Akron: ['Akron', 'AKR', 'Zips'],
    'Ball State': ['Ball State', 'BALL', 'Cardinals'],
    'Bowling Green': ['Bowling Green', 'BGSU', 'BG', 'Falcons'],
    Buffalo: ['Buffalo', 'BUFF', 'Bulls'],
    'Central Michigan': ['Central Michigan', 'CMU', 'Chippewas'],
    'Eastern Michigan': ['Eastern Michigan', 'EMU', 'Eagles'],
    'Kent State': ['Kent State', 'KENT', 'Golden Flashes'],
    'Miami Ohio': ['Miami Ohio', 'MIA-OH', 'MIAMI', 'RedHawks', 'Miami (OH)'],
    'Northern Illinois': ['Northern Illinois', 'NIU', 'Huskies'],
    Ohio: ['Ohio', 'OHIO', 'Bobcats', 'Ohio Bobcats'],
    Toledo: ['Toledo', 'TOL', 'Rockets'],
    'Western Michigan': ['Western Michigan', 'WMU', 'Broncos'],

    // AAC
    Army: ['Army', 'ARMY', 'Black Knights'],
    Charlotte: ['Charlotte', 'CLT', '49ers'],
    'East Carolina': ['East Carolina', 'ECU', 'Pirates'],
    FAU: ['FAU', 'Florida Atlantic', 'Owls'],
    Memphis: ['Memphis', 'MEM', 'Tigers'],
    Navy: ['Navy', 'NAVY', 'Midshipmen'],
    'North Texas': ['North Texas', 'UNT', 'Mean Green'],
    Rice: ['Rice', 'RICE', 'Owls'],
    'South Florida': ['South Florida', 'USF', 'Bulls'],
    Temple: ['Temple', 'TEM', 'Owls'],
    Tulane: ['Tulane', 'TUL', 'Green Wave'],
    Tulsa: ['Tulsa', 'TLSA', 'Golden Hurricane'],
    UAB: ['UAB', 'Alabama Birmingham', 'Blazers'],
    UTSA: ['UTSA', 'Texas San Antonio', 'Roadrunners'],

    // Independents
    UConn: ['UConn', 'Connecticut', 'CONN', 'Huskies'],
    UMass: ['UMass', 'Massachusetts', 'Minutemen'],

    // SEC
    Alabama: ['Alabama', 'Crimson Tide', 'Bama', 'ALA', 'Roll Tide'],
    Arkansas: ['Arkansas', 'Razorbacks', 'Hogs', 'ARK'],
    Auburn: ['Auburn', 'Tigers', 'AUB', 'War Eagle'],
    Florida: ['Florida', 'Gators', 'UF', 'FLA'],
    Georgia: ['Georgia', 'UGA', 'Dawgs', 'Georgia Bulldogs'],
    Kentucky: ['Kentucky', 'Wildcats', 'UK', 'KY', 'KEN'],
    LSU: ['LSU', 'Tigers', 'Louisiana State', 'Geaux Tigers'],
    'Mississippi State': ['Mississippi State', 'Miss St', 'MSST', 'Bulldogs'],
    Missouri: ['Missouri', 'Mizzou', 'MIZ', 'MU', 'Tigers'],
    Oklahoma: ['Oklahoma', 'Sooners', 'OU', 'OKL', 'Boomer'],
    'Ole Miss': ['Ole Miss', 'Mississippi', 'Rebels', 'MISS', 'UM'],
    'South Carolina': ['South Carolina', 'Gamecocks', 'SCAR', 'SC'],
    Tennessee: ['Tennessee', 'Volunteers', 'Vols', 'TENN', 'UT'],
    Texas: ['Texas', 'Longhorns', 'TEX', 'Hook Em'],
    'Texas A&M': ['Texas A&M', 'Aggies', 'TAMU', 'A&M', 'ATM'],
    Vanderbilt: ['Vanderbilt', 'Commodores', 'VANDY', 'VAN'],

    // Big Ten
    Illinois: ['Illinois', 'Fighting Illini', 'ILL', 'UI', 'Illini'],
    Indiana: ['Indiana', 'Hoosiers', 'IND', 'IU'],
    Iowa: ['Iowa', 'Hawkeyes', 'IOWA', 'UI'],
    Maryland: ['Maryland', 'Terps', 'Terrapins', 'MD', 'UMD'],
    Michigan: ['Michigan', 'Wolverines', 'MICH', 'UM'],
    'Michigan State': ['Michigan State', 'Spartans', 'MSU', 'Mich St'],
    Minnesota: ['Minnesota', 'Golden Gophers', 'Gophers', 'MINN', 'UM'],
    Nebraska: ['Nebraska', 'Huskers', 'Cornhuskers', 'NEB', 'NU'],
    Northwestern: ['Northwestern', 'Wildcats', 'NW', 'NWU', 'NWST'],
    'Ohio State': ['Ohio State', 'Buckeyes', 'OSU', 'tOSU', 'Ohio St'],
    Oregon: ['Oregon', 'Ducks', 'ORE', 'UO'],
    'Penn State': ['Penn State', 'Nittany Lions', 'PSU', 'Penn St'],
    Purdue: ['Purdue', 'Boilermakers', 'PUR', 'PU'],
    Rutgers: ['Rutgers', 'Scarlet Knights', 'RUT', 'RU'],
    UCLA: ['UCLA', 'Bruins'],
    USC: ['USC', 'Trojans', 'Southern Cal'],
    Washington: ['Washington', 'Huskies', 'WASH', 'UW'],
    Wisconsin: ['Wisconsin', 'Badgers', 'WIS', 'UW'],

    // Big 12
    Arizona: ['Arizona', 'Wildcats', 'ARIZ', 'UA', 'Zona'],
    'Arizona State': ['Arizona State', 'Sun Devils', 'ASU', 'AZ State'],
    Baylor: ['Baylor', 'Bears', 'BAY', 'BU'],
    BYU: ['BYU', 'Cougars', 'Brigham Young'],
    Cincinnati: ['Cincinnati', 'Bearcats', 'CIN', 'UC', 'Cincy'],
    Colorado: ['Colorado', 'Buffaloes', 'Buffs', 'COLO', 'CU'],
    Houston: ['Houston', 'Cougars', 'HOU', 'UH'],
    'Iowa State': ['Iowa State', 'Cyclones', 'ISU', 'Iowa St'],
    Kansas: ['Kansas', 'Jayhawks', 'KU', 'KAN'],
    'Kansas State': ['Kansas State', 'Wildcats', 'KSU', 'K-State', 'KState'],
    'Oklahoma State': ['Oklahoma State', 'Cowboys', 'OKST', 'OSU', 'Okla St', 'Pokes'],
    TCU: ['TCU', 'Horned Frogs', 'Texas Christian'],
    'Texas Tech': ['Texas Tech', 'Red Raiders', 'TT', 'TTU'],
    UCF: ['UCF', 'Knights', 'Central Florida'],
    Utah: ['Utah', 'Utes', 'UTAH', 'UTA', 'UU'],
    'West Virginia': ['West Virginia', 'Mountaineers', 'WVU', 'WV'],

    // ACC
    'Boston College': ['Boston College', 'BC', 'Eagles'],
    California: ['California', 'Cal', 'Golden Bears', 'CAL', 'UC Berkeley'],
    Clemson: ['Clemson', 'Tigers', 'CLEM', 'CU'],
    Duke: ['Duke', 'Blue Devils', 'DUKE'],
    'Florida State': ['Florida State', 'Seminoles', 'FSU', 'Fla St', 'Noles'],
    Louisville: ['Louisville', 'Cardinals', 'Lou', 'LOU', 'UL'],
    'Miami (FL)': ['Miami', 'Hurricanes', 'MIA', 'UM', 'Canes'],
    'NC State': ['NC State', 'Wolfpack', 'NCST', 'NCS', 'North Carolina State'],
    'North Carolina': ['North Carolina', 'Tar Heels', 'UNC', 'Carolina'],
    'Notre Dame': ['Notre Dame', 'Irish', 'ND', 'Fighting Irish'],
    Pittsburgh: ['Pittsburgh', 'Panthers', 'Pitt', 'PITT'],
    SMU: ['SMU', 'Mustangs', 'Southern Methodist'],
    Stanford: ['Stanford', 'Cardinal', 'STAN'],
    Syracuse: ['Syracuse', 'Orange', 'SYR', 'Cuse'],
    Virginia: ['Virginia', 'Cavaliers', 'UVA', 'VA', 'Hoos'],
    'Virginia Tech': ['Virginia Tech', 'Hokies', 'VT', 'Va Tech'],
    'Wake Forest': ['Wake Forest', 'Demon Deacons', 'Wake', 'WAKE', 'WF'],
  },
  NCAAB: {
    // Liberty (must check before WNBA Liberty)
    'Liberty (NCAAB)': ['Liberty', 'LIB', 'Liberty Flames', 'Flames'],

    // Big East
    Butler: ['Butler', 'BUT', 'Bulldogs'],
    Creighton: ['Creighton', 'CREI', 'Bluejays'],
    DePaul: ['DePaul', 'DEPL', 'Blue Demons'],
    Georgetown: ['Georgetown', 'GTWN', 'GU', 'Hoyas'],
    Marquette: ['Marquette', 'MARQ', 'MU', 'Golden Eagles'],
    Providence: ['Providence', 'PROV', 'Friars'],
    'Seton Hall': ['Seton Hall', 'HALL', 'SHU', 'Pirates'],
    "St. John's": ["St. John's", 'STJ', 'STJN', 'Red Storm'],
    UConn: ['UConn', 'Connecticut', 'CONN', 'Huskies'],
    Villanova: ['Villanova', 'Nova', 'VILL', 'Wildcats'],
    Xavier: ['Xavier', 'XAV', 'Musketeers'],

    // WCC
    Gonzaga: ['Gonzaga', 'Gonz', 'GONZ', 'GU', 'Zags', 'Bulldogs'],
    "Saint Mary's": ["Saint Mary's", 'SMC', 'Gaels', 'St Marys'],
    'San Francisco': ['San Francisco', 'USF', 'Dons', 'SF Dons'],
    'Santa Clara': ['Santa Clara', 'SCU', 'Broncos'],
    Pepperdine: ['Pepperdine', 'PEPP', 'Waves'],
    Pacific: ['Pacific', 'PAC', 'Tigers'],
    Portland: ['Portland', 'PORT', 'UP', 'Pilots'],
    'Loyola Marymount': ['Loyola Marymount', 'LMU', 'Lions'],

    // A10
    Dayton: ['Dayton', 'DAY', 'UD', 'Flyers'],
    VCU: ['VCU', 'Virginia Commonwealth', 'Rams'],
    'Saint Louis': ['Saint Louis', 'SLU', 'Billikens', 'St Louis'],
    Richmond: ['Richmond', 'RICH', 'Spiders'],
    'George Mason': ['George Mason', 'GMU', 'Patriots'],
    Davidson: ['Davidson', 'DAV', 'Wildcats'],
    'La Salle': ['La Salle', 'LAS', 'Explorers'],
    'Rhode Island': ['Rhode Island', 'URI', 'Rams'],
    'St. Bonaventure': ['St. Bonaventure', 'BONN', 'SBU', 'Bonnies'],
    UMass: ['UMass', 'Massachusetts', 'Minutemen'],

    // MVC
    Drake: ['Drake', 'DRAKE', 'Bulldogs'],
    'Loyola Chicago': ['Loyola Chicago', 'LUC', 'Ramblers'],
    Bradley: ['Bradley', 'BRAD', 'Braves'],
    'Indiana State': ['Indiana State', 'INST', 'Sycamores'],
    'Southern Illinois': ['Southern Illinois', 'SIU', 'Salukis'],
    'Missouri State': ['Missouri State', 'MOST', 'Bears'],
    Evansville: ['Evansville', 'EVAN', 'Purple Aces'],
    'Northern Iowa': ['Northern Iowa', 'UNI', 'Panthers'],
    'Illinois State': ['Illinois State', 'ILST', 'Redbirds'],
    Valparaiso: ['Valparaiso', 'VALP', 'Beacons'],
    'Murray State': ['Murray State', 'MURR', 'Racers'],
    Belmont: ['Belmont', 'BELM', 'Bruins'],

    // Ivy League
    Princeton: ['Princeton', 'PRIN', 'Tigers'],
    Yale: ['Yale', 'YALE', 'Bulldogs'],
    Harvard: ['Harvard', 'HARV', 'Crimson'],
    Penn: ['Penn', 'Pennsylvania', 'PENN', 'Quakers'],
    Cornell: ['Cornell', 'CORN', 'Big Red'],
    Columbia: ['Columbia', 'COLM', 'Lions'],
    Brown: ['Brown', 'BRWN', 'Bears'],
    Dartmouth: ['Dartmouth', 'DART', 'Big Green'],

    // Other Notable
    'Wichita State': ['Wichita State', 'Wichita', 'WICH', 'Shockers'],
    'Oral Roberts': ['Oral Roberts', 'ORU', 'Golden Eagles'],
    'Grand Canyon': ['Grand Canyon', 'GCU', 'Antelopes'],
    Iona: ['Iona', 'IONA', 'Gaels'],
    'Fairleigh Dickinson': ['Fairleigh Dickinson', 'FDU', 'Knights'],
    Vermont: ['Vermont', 'UVM', 'Catamounts'],
    FGCU: ['FGCU', 'Florida Gulf Coast', 'Eagles'],
    'Middle Tennessee': ['Middle Tennessee', 'MTSU', 'Blue Raiders'],
    'Western Kentucky': ['Western Kentucky', 'WKU', 'Hilltoppers'],
    UAB: ['UAB', 'Alabama Birmingham', 'Blazers'],
    'New Mexico State': ['New Mexico State', 'NMSU', 'Aggies'],
    "Saint Peter's": ["Saint Peter's", 'SPU', 'Peacocks'],
    Mercer: ['Mercer', 'MERC', 'Bears'],
    Colgate: ['Colgate', 'COLG', 'Raiders'],
    Winthrop: ['Winthrop', 'WIN', 'Eagles'],
    'UL Lafayette': ['UL Lafayette', 'Louisiana Lafayette', 'ULL', 'Ragin Cajuns'],
    'UL Monroe': ['UL Monroe', 'Louisiana Monroe', 'ULM', 'Warhawks'],
    'Washington State': ['Washington State', 'Wazzu', 'WSU', 'Cougars'],
    Seattle: ['Seattle', 'Seattle U', 'Redhawks'],

    // Power conference teams (use NCAAF mappings where applicable)
    Duke: ['Duke', 'Blue Devils', 'DUKE'],
    'North Carolina': ['North Carolina', 'Tar Heels', 'UNC', 'Carolina'],
    Kentucky: ['Kentucky', 'Wildcats', 'UK', 'KY'],
    Kansas: ['Kansas', 'Jayhawks', 'KU'],
    UCLA: ['UCLA', 'Bruins'],
    Purdue: ['Purdue', 'Boilermakers', 'PUR'],
    Arizona: ['Arizona', 'Wildcats', 'ARIZ', 'UA'],
    Houston: ['Houston', 'Cougars', 'HOU', 'UH'],
    Baylor: ['Baylor', 'Bears', 'BAY'],
    Tennessee: ['Tennessee', 'Volunteers', 'Vols', 'TENN'],
    Alabama: ['Alabama', 'Crimson Tide', 'Bama', 'ALA'],
    Indiana: ['Indiana', 'Hoosiers', 'IND', 'IU'],
    'Michigan State': ['Michigan State', 'Spartans', 'MSU'],
    Michigan: ['Michigan', 'Wolverines', 'MICH'],
    Syracuse: ['Syracuse', 'Orange', 'SYR', 'Cuse'],
    Louisville: ['Louisville', 'Cardinals', 'Lou', 'LOU'],
    Florida: ['Florida', 'Gators', 'UF'],
    Auburn: ['Auburn', 'Tigers', 'AUB'],
    Arkansas: ['Arkansas', 'Razorbacks', 'ARK'],
    'Texas Tech': ['Texas Tech', 'Red Raiders', 'TTU'],
    Texas: ['Texas', 'Longhorns', 'TEX'],
    'Ohio State': ['Ohio State', 'Buckeyes', 'OSU'],
    Illinois: ['Illinois', 'Fighting Illini', 'ILL'],
    Iowa: ['Iowa', 'Hawkeyes', 'IOWA'],
    Oregon: ['Oregon', 'Ducks', 'ORE'],
  },
};

/**
 * Standardize a team name to its canonical form
 * Checks longer/more specific names first to avoid false matches
 */
export function standardizeTeamName(team: string, sport: string): string {
  const sportMappings = teamMappings[sport] || {};
  const teamLower = team.toLowerCase();

  // Sort entries by the length of the longest variation (longest first)
  // This ensures "Georgia Southern" matches before "Georgia"
  const sortedEntries = Object.entries(sportMappings).sort((a, b) => {
    const maxLenA = Math.max(...a[1].map(v => v.length));
    const maxLenB = Math.max(...b[1].map(v => v.length));
    return maxLenB - maxLenA;
  });

  for (const [standardName, variations] of sortedEntries) {
    if (variations.some(v => teamLower.includes(v.toLowerCase()))) {
      return standardName;
    }
  }

  return team.trim();
}

/**
 * Identify sport from team name
 */
export function identifySport(team: string): string | null {
  for (const [sport, teams] of Object.entries(teamMappings)) {
    for (const variations of Object.values(teams)) {
      if (variations.some(v => team.toLowerCase().includes(v.toLowerCase()))) {
        return sport;
      }
    }
  }
  return null;
}
