// Team name mappings from your ConsensusProject
// Used for standardizing team names before counting consensus

export const teamMappings: Record<string, Record<string, string[]>> = {
  MLB: {
    Diamondbacks: ['Diamondbacks', 'Arizona', 'Dbacks', 'ARI'],
    Braves: ['Braves', 'Atlanta', 'ATL'],
    Orioles: ['Orioles', 'Baltimore', 'BAL'],
    'Red Sox': ['Red Sox', 'Boston', 'BOS'],
    Cubs: ['Cubs', 'Chicago Cubs', 'CHC'],
    'White Sox': ['White Sox', 'Chicago White Sox', 'CWS'],
    Reds: ['Reds', 'Cincinnati', 'CIN'],
    Guardians: ['Guardians', 'Cleveland', 'CLE'],
    Rockies: ['Rockies', 'Colorado', 'COL'],
    Tigers: ['Tigers', 'Detroit', 'DET'],
    Astros: ['Astros', 'Houston', 'HOU'],
    Royals: ['Royals', 'Kansas City', 'KC'],
    Angels: ['Angels', 'Los Angeles Angels', 'LAA'],
    Dodgers: ['Dodgers', 'Los Angeles Dodgers', 'LAD'],
    Marlins: ['Marlins', 'Miami', 'MIA'],
    Brewers: ['Brewers', 'Milwaukee', 'MIL'],
    Twins: ['Twins', 'Minnesota', 'MIN'],
    Yankees: ['Yankees', 'New York Yankees', 'NYY'],
    Mets: ['Mets', 'New York Mets', 'NYM'],
    Athletics: ['Athletics', 'Oakland', "A's", 'OAK'],
    Phillies: ['Phillies', 'Philadelphia', 'PHI'],
    Pirates: ['Pirates', 'Pittsburgh', 'PIT'],
    Padres: ['Padres', 'San Diego', 'SD'],
    Giants: ['Giants', 'San Francisco', 'SF'],
    Mariners: ['Mariners', 'Seattle', 'SEA'],
    Cardinals: ['Cardinals', 'St Louis', 'STL', 'St. Louis'],
    Rays: ['Rays', 'Tampa Bay', 'TB'],
    Rangers: ['Rangers', 'Texas', 'TEX'],
    'Blue Jays': ['Blue Jays', 'Toronto', 'TOR'],
    Nationals: ['Nationals', 'Washington', 'WAS'],
  },
  NBA: {
    Hawks: ['Hawks', 'Atlanta', 'ATL'],
    Celtics: ['Celtics', 'Boston', 'BOS'],
    Nets: ['Nets', 'Brooklyn', 'BKN'],
    Hornets: ['Hornets', 'Charlotte', 'CHA'],
    Bulls: ['Bulls', 'Chicago', 'CHI'],
    Cavaliers: ['Cavaliers', 'Cleveland', 'CLE', 'Cavs', 'Cavliers'],
    Mavericks: ['Mavericks', 'Dallas', 'DAL', 'Mavs'],
    Nuggets: ['Nuggets', 'Denver', 'DEN'],
    Pistons: ['Pistons', 'Detroit', 'DET'],
    Warriors: ['Warriors', 'Golden State', 'GS', 'GSW'],
    Rockets: ['Rockets', 'Houston', 'HOU'],
    Pacers: ['Pacers', 'Indiana', 'IND'],
    Clippers: ['Clippers', 'Los Angeles Clippers', 'LAC'],
    Lakers: ['Lakers', 'Los Angeles Lakers', 'LAL'],
    Grizzlies: ['Grizzlies', 'Memphis', 'MEM'],
    Heat: ['Heat', 'Miami', 'MIA'],
    Bucks: ['Bucks', 'Milwaukee', 'MIL'],
    Timberwolves: ['Timberwolves', 'Minnesota', 'MIN', 'Wolves', 'Twolves', "T'Wolves", 'T-Wolves'],
    Pelicans: ['Pelicans', 'New Orleans', 'NO', 'NOP'],
    Knicks: ['Knicks', 'New York', 'NY', 'NYK'],
    Thunder: ['Thunder', 'Oklahoma City', 'OKC'],
    Magic: ['Magic', 'Orlando', 'ORL'],
    '76ers': ['76ers', 'Philadelphia', 'PHI', 'Sixers'],
    Suns: ['Suns', 'Phoenix', 'PHX'],
    'Trail Blazers': ['Trail Blazers', 'Portland', 'POR', 'Blazers'],
    Kings: ['Kings', 'Sacramento', 'SAC'],
    Spurs: ['Spurs', 'San Antonio', 'SA', 'SAS'],
    Raptors: ['Raptors', 'Toronto', 'TOR'],
    Jazz: ['Jazz', 'Utah', 'UTA'],
    Wizards: ['Wizards', 'Washington', 'WAS'],
  },
  NFL: {
    Cardinals: ['Cardinals', 'Arizona', 'ARI'],
    Falcons: ['Falcons', 'Atlanta', 'ATL'],
    Ravens: ['Ravens', 'Baltimore', 'BAL'],
    Bills: ['Bills', 'Buffalo', 'BUF'],
    Panthers: ['Panthers', 'Carolina', 'CAR'],
    Bears: ['Bears', 'Chicago', 'CHI'],
    Bengals: ['Bengals', 'Cincinnati', 'CIN'],
    Browns: ['Browns', 'Cleveland', 'CLE'],
    Cowboys: ['Cowboys', 'Dallas', 'DAL'],
    Broncos: ['Broncos', 'Denver', 'DEN'],
    Lions: ['Lions', 'Detroit', 'DET'],
    Packers: ['Packers', 'Green Bay', 'GB'],
    Texans: ['Texans', 'Houston', 'HOU'],
    Colts: ['Colts', 'Indianapolis', 'IND'],
    Jaguars: ['Jaguars', 'Jacksonville', 'JAX', 'JAC'],
    Chiefs: ['Chiefs', 'Kansas City', 'KC'],
    Raiders: ['Raiders', 'Las Vegas', 'LV', 'Oakland'],
    Chargers: ['Chargers', 'Los Angeles Chargers', 'LAC'],
    Rams: ['Rams', 'Los Angeles Rams', 'LAR', 'LA'],
    Dolphins: ['Dolphins', 'Miami', 'MIA'],
    Vikings: ['Vikings', 'Minnesota', 'MIN'],
    Patriots: ['Patriots', 'New England', 'NE'],
    Saints: ['Saints', 'New Orleans', 'NO'],
    'Giants (NFL)': ['Giants', 'New York Giants', 'NYG'],
    'Jets (NFL)': ['Jets', 'New York Jets', 'NYJ'],
    Eagles: ['Eagles', 'Philadelphia', 'PHI'],
    Steelers: ['Steelers', 'Pittsburgh', 'PIT'],
    '49ers': ['49ers', 'San Francisco', 'SF', 'Niners'],
    Seahawks: ['Seahawks', 'Seattle', 'SEA'],
    Buccaneers: ['Buccaneers', 'Tampa Bay', 'TB', 'Bucs'],
    Titans: ['Titans', 'Tennessee', 'TEN'],
    Commanders: ['Commanders', 'Washington', 'WAS'],
  },
  NHL: {
    Ducks: ['Ducks', 'Anaheim', 'ANA'],
    Coyotes: ['Coyotes', 'Arizona', 'ARI', 'Utah Hockey'],
    Bruins: ['Bruins', 'Boston', 'BOS'],
    Sabres: ['Sabres', 'Buffalo', 'BUF'],
    Flames: ['Flames', 'Calgary', 'CGY'],
    Hurricanes: ['Hurricanes', 'Carolina', 'CAR'],
    Blackhawks: ['Blackhawks', 'Chicago', 'CHI'],
    Avalanche: ['Avalanche', 'Colorado', 'COL'],
    'Blue Jackets': ['Blue Jackets', 'Columbus', 'CBJ'],
    Stars: ['Stars', 'Dallas', 'DAL'],
    'Red Wings': ['Red Wings', 'Detroit', 'DET'],
    Oilers: ['Oilers', 'Edmonton', 'EDM'],
    'Panthers (NHL)': ['Panthers', 'Florida', 'FLA'],
    'Kings (NHL)': ['Kings', 'Los Angeles', 'LA'],
    Wild: ['Wild', 'Minnesota', 'MIN'],
    Canadiens: ['Canadiens', 'Montreal', 'MTL', 'Habs'],
    Predators: ['Predators', 'Nashville', 'NSH'],
    Devils: ['Devils', 'New Jersey', 'NJ', 'NJD'],
    Islanders: ['Islanders', 'New York Islanders', 'NYI'],
    'Rangers (NHL)': ['Rangers', 'New York Rangers', 'NYR'],
    Senators: ['Senators', 'Ottawa', 'OTT'],
    Flyers: ['Flyers', 'Philadelphia', 'PHI'],
    Penguins: ['Penguins', 'Pittsburgh', 'PIT'],
    Sharks: ['Sharks', 'San Jose', 'SJ', 'SJS'],
    Kraken: ['Kraken', 'Seattle', 'SEA'],
    Blues: ['Blues', 'St Louis', 'STL', 'St. Louis'],
    Lightning: ['Lightning', 'Tampa Bay', 'TB', 'TBL'],
    'Maple Leafs': ['Maple Leafs', 'Toronto', 'TOR'],
    Canucks: ['Canucks', 'Vancouver', 'VAN'],
    'Golden Knights': ['Golden Knights', 'Vegas', 'VGK'],
    Capitals: ['Capitals', 'Washington', 'WAS', 'Caps'],
    'Jets (NHL)': ['Jets', 'Winnipeg', 'WPG'],
  },
  WNBA: {
    Dream: ['Dream', 'Atlanta'],
    Sky: ['Sky', 'Chicago'],
    Fever: ['Fever', 'Indiana'],
    Sun: ['Sun', 'Connecticut'],
    Wings: ['Wings', 'Dallas'],
    Sparks: ['Sparks', 'Los Angeles'],
    Aces: ['Aces', 'Las Vegas'],
    Lynx: ['Lynx', 'Minnesota'],
    Liberty: ['Liberty', 'New York'],
    Mercury: ['Mercury', 'Phoenix'],
    Storm: ['Storm', 'Seattle'],
    Mystics: ['Mystics', 'Washington'],
  },
  NCAAF: {
    // Bowl Games & Common Teams
    // IMPORTANT: More specific names must come BEFORE shorter ones to avoid false matches
    'Georgia Southern': ['Georgia Southern', 'Georgia Southern Eagles', 'GSU', 'GASO'],
    'Georgia Tech': ['Georgia Tech', 'Yellow Jackets', 'GT'],
    'Georgia State': ['Georgia State', 'Panthers', 'GSU'],
    Hawaii: ['Hawaii', 'Rainbow Warriors', 'Hawaii Rainbow Warriors', 'HAW'],
    California: ['California', 'Cal', 'Golden Bears', 'CAL', 'California Golden Bears'],
    Alabama: ['Alabama', 'Crimson Tide', 'Bama', 'ALA'],
    Georgia: ['Georgia', 'UGA', 'Georgia Bulldogs'],
    'Ohio State': ['Ohio State', 'Buckeyes', 'OSU'],
    Michigan: ['Michigan', 'Wolverines', 'MICH'],
    Texas: ['Texas', 'Longhorns', 'TEX'],
    Oklahoma: ['Oklahoma', 'Sooners', 'OU'],
    USC: ['USC', 'Trojans', 'Southern Cal'],
    Oregon: ['Oregon', 'Ducks', 'ORE'],
    'Notre Dame': ['Notre Dame', 'Irish', 'ND'],
    Clemson: ['Clemson', 'Tigers', 'CLEM'],
    LSU: ['LSU', 'Tigers', 'Louisiana State'],
    Florida: ['Florida', 'Gators', 'UF'],
    'Penn State': ['Penn State', 'Nittany Lions', 'PSU'],
    Tennessee: ['Tennessee', 'Volunteers', 'Vols', 'TENN'],
    'Texas A&M': ['Texas A&M', 'Aggies', 'TAMU'],
    Auburn: ['Auburn', 'Tigers', 'AUB'],
    'Miami (FL)': ['Miami', 'Hurricanes', 'MIA'],
    'Michigan State': ['Michigan State', 'Spartans', 'MSU'],
    Wisconsin: ['Wisconsin', 'Badgers', 'WIS'],
    Iowa: ['Iowa', 'Hawkeyes', 'IOWA'],
    'Arizona State': ['Arizona State', 'Sun Devils', 'ASU'],
    Arizona: ['Arizona', 'Wildcats', 'ARIZ'],
    Utah: ['Utah', 'Utes', 'UTAH'],
    Colorado: ['Colorado', 'Buffaloes', 'Buffs', 'COLO'],
    Washington: ['Washington', 'Huskies', 'WASH', 'UW'],
    UCLA: ['UCLA', 'Bruins'],
    Stanford: ['Stanford', 'Cardinal', 'STAN'],
    Northwestern: ['Northwestern', 'Wildcats', 'NW'],
    'Central Michigan': ['Central Michigan', 'Chippewas', 'CMU'],
    'New Mexico': ['New Mexico', 'Lobos', 'NM'],
    Minnesota: ['Minnesota', 'Golden Gophers', 'Gophers', 'MINN'],
    Syracuse: ['Syracuse', 'Orange', 'SYR'],
    Louisville: ['Louisville', 'Cardinals', 'LOU'],
    Kentucky: ['Kentucky', 'Wildcats', 'UK'],
    Vanderbilt: ['Vanderbilt', 'Commodores', 'VANDY'],
    'South Carolina': ['South Carolina', 'Gamecocks', 'USC', 'SCAR'],
    Missouri: ['Missouri', 'Tigers', 'MIZZ', 'MIZ'],
    Arkansas: ['Arkansas', 'Razorbacks', 'Hogs', 'ARK'],
    'Mississippi State': ['Mississippi State', 'Bulldogs', 'MSU', 'MSST'],
    'Ole Miss': ['Ole Miss', 'Mississippi', 'Rebels', 'MISS'],
    Baylor: ['Baylor', 'Bears', 'BAY'],
    TCU: ['TCU', 'Horned Frogs', 'Texas Christian'],
    Kansas: ['Kansas', 'Jayhawks', 'KU'],
    'Kansas State': ['Kansas State', 'Wildcats', 'KSU'],
    'Iowa State': ['Iowa State', 'Cyclones', 'ISU'],
    'Oklahoma State': ['Oklahoma State', 'Cowboys', 'OKST'],
    'West Virginia': ['West Virginia', 'Mountaineers', 'WVU'],
    Cincinnati: ['Cincinnati', 'Bearcats', 'CIN'],
    UCF: ['UCF', 'Knights', 'Central Florida'],
    Houston: ['Houston', 'Cougars', 'HOU'],
    BYU: ['BYU', 'Cougars', 'Brigham Young'],
    Boise: ['Boise', 'Boise State', 'Broncos', 'BSU'],
    Memphis: ['Memphis', 'Tigers', 'MEM'],
    SMU: ['SMU', 'Mustangs', 'Southern Methodist'],
    Tulane: ['Tulane', 'Green Wave', 'TUL'],
    Navy: ['Navy', 'Midshipmen', 'NAVY'],
    Army: ['Army', 'Black Knights', 'ARMY'],
    'Air Force': ['Air Force', 'Falcons', 'AFA'],
  },
  NCAAB: {
    // Common College Basketball Teams
    Duke: ['Duke', 'Blue Devils', 'DUKE'],
    'North Carolina': ['North Carolina', 'Tar Heels', 'UNC'],
    Kentucky: ['Kentucky', 'Wildcats', 'UK'],
    Kansas: ['Kansas', 'Jayhawks', 'KU'],
    Gonzaga: ['Gonzaga', 'Bulldogs', 'GONZ', 'Zags'],
    Villanova: ['Villanova', 'Wildcats', 'NOVA'],
    UCLA: ['UCLA', 'Bruins'],
    UConn: ['UConn', 'Connecticut', 'Huskies', 'CONN'],
    Purdue: ['Purdue', 'Boilermakers', 'PUR'],
    Arizona: ['Arizona', 'Wildcats', 'ARIZ'],
    Houston: ['Houston', 'Cougars', 'HOU'],
    Baylor: ['Baylor', 'Bears', 'BAY'],
    Tennessee: ['Tennessee', 'Volunteers', 'Vols', 'TENN'],
    Alabama: ['Alabama', 'Crimson Tide', 'ALA'],
    Indiana: ['Indiana', 'Hoosiers', 'IND'],
    'Michigan State': ['Michigan State', 'Spartans', 'MSU'],
    Michigan: ['Michigan', 'Wolverines', 'MICH'],
    Syracuse: ['Syracuse', 'Orange', 'SYR'],
    Louisville: ['Louisville', 'Cardinals', 'LOU'],
    Florida: ['Florida', 'Gators', 'UF'],
    Auburn: ['Auburn', 'Tigers', 'AUB'],
    Marquette: ['Marquette', 'Golden Eagles', 'MARQ'],
    Creighton: ['Creighton', 'Bluejays', 'CREI'],
    'San Diego State': ['San Diego State', 'Aztecs', 'SDSU'],
    FAU: ['FAU', 'Florida Atlantic', 'Owls'],
    Xavier: ['Xavier', 'Musketeers', 'XAV'],
    Iowa: ['Iowa', 'Hawkeyes', 'IOWA'],
    Illinois: ['Illinois', 'Fighting Illini', 'ILL'],
    Arkansas: ['Arkansas', 'Razorbacks', 'ARK'],
    'Texas Tech': ['Texas Tech', 'Red Raiders', 'TTU'],
    Texas: ['Texas', 'Longhorns', 'TEX'],
    'Ohio State': ['Ohio State', 'Buckeyes', 'OSU'],
  },
};

/**
 * Standardize a team name to its canonical form
 * Checks longer/more specific names first to avoid false matches
 */
export function standardizeTeamName(team: string, sport: string): string {
  const sportMappings = teamMappings[sport] || {};
  const teamLower = team.toLowerCase();

  // Sort entries by the length of variations (longest first) to match specific names first
  // e.g., "Georgia Southern" should match before "Georgia"
  const sortedEntries = Object.entries(sportMappings).sort((a, b) => {
    const maxLenA = Math.max(...a[1].map(v => v.length));
    const maxLenB = Math.max(...b[1].map(v => v.length));
    return maxLenB - maxLenA; // Longest first
  });

  for (const [standardName, variations] of sortedEntries) {
    if (variations.some(v => teamLower.includes(v.toLowerCase()))) {
      return standardName;
    }
  }

  return team.trim();
}

/**
 * Identify sport from team name
 */
export function identifySport(team: string): string | null {
  for (const [sport, teams] of Object.entries(teamMappings)) {
    for (const variations of Object.values(teams)) {
      if (variations.some(v => team.toLowerCase().includes(v.toLowerCase()))) {
        return sport;
      }
    }
  }
  return null;
}
